name: STpath-env
channels:
  - defaults
dependencies:
  - pip=21.2.2
  - python=3.9.6
  - pip:
      - argparse==0.10.2
      - opencv-python==4.6.0.66
      - h5py==3.10.0
      - json5==0.9.8
      - matplotlib==3.4.3
      - matplotlib-inline==0.1.2
      - numpy==1.26.4
      - pandas==2.2.0
      - Pillow==8.3.2
      - scikit-image==0.19.3
      - scikit-learn==1.4.0
      - seaborn==0.11.2
      - tensorflow==2.7.1
      - tifffile==2021.11.2
      - torch==2.2.0
      - torchvision==0.1.8
      - torch-staintools=1.0.4
